name: smart_nav_bar
description: A customizable bottom navigation bar for Flutter with smooth animations and flexible styling options.
version: 1.0.4+5
homepage: https://github.com/Halawany1/smart_nav_bar

license: MIT 
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/